import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle, Circle, AlertTriangle, TrendingUp, ChevronDown, ChevronUp, Download } from 'lucide-react';
import { EKG_CHECKLIST, evaluateEKGHealth } from '../data/ekgHealthData';
import ScoreRing from '../components/ScoreRing';
import RadarChart from '../components/RadarChart';

export default function EKGHealthPage() {
  const [checkedItems, setCheckedItems] = useState([]);
  const [results, setResults] = useState(null);
  const [expandedCat, setExpandedCat] = useState(EKG_CHECKLIST.map(c => c.id));

  const toggleItem = (id) => {
    setCheckedItems(prev =>
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const toggleCat = (id) => {
    setExpandedCat(prev =>
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const handleEvaluate = () => {
    setResults(evaluateEKGHealth(checkedItems));
  };

  const handleExport = () => {
    if (!results) return;
    const lines = [];
    lines.push('=== EKG Health Check Report ===');
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push('');
    lines.push(`Overall Score: ${results.overallScore}%`);
    lines.push('');
    lines.push('--- Category Scores ---');
    Object.entries(results.categoryScores).forEach(([cat, score]) => {
      lines.push(`  ${cat}: ${score}%`);
    });
    lines.push('');
    if (results.findings.length > 0) {
      lines.push(`--- Findings (${results.findings.length}) ---`);
      results.findings.forEach((f, i) => {
        lines.push(`  ${i + 1}. [${f.severity.toUpperCase()}] ${f.issue}`);
        lines.push(`     Category: ${f.category}`);
      });
    } else {
      lines.push('No critical findings. All checks passed!');
    }
    lines.push('');
    lines.push('--- Checked Items ---');
    lines.push(`  ${checkedItems.length} of ${totalItems} items checked`);
    lines.push('');
    lines.push('Report generated by o9 Optimizer Agent');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ekg-health-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const totalItems = EKG_CHECKLIST.reduce((s, c) => s + c.items.length, 0);

  const radarData = results
    ? Object.entries(results.categoryScores).map(([label, value]) => ({ label, value }))
    : [];

  return (
    <div className="section" style={{ background: 'white', minHeight: '80vh' }}>
      <div className="analyzer-container">
        <div className="section-header">
          <h2>EKG Health Checker</h2>
          <p>
            Audit your Enterprise Knowledge Graph configuration against o9 best practices.
            Check each item that applies to your current implementation.
          </p>
        </div>

        {/* Checklist */}
        <div className="analyzer-form" style={{ marginBottom: 24 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
              {checkedItems.length} of {totalItems} items checked
            </p>
            <div className="progress-bar" style={{ width: 200 }}>
              <div className="progress-bar-fill" style={{ width: `${(checkedItems.length / totalItems) * 100}%` }} />
            </div>
          </div>

          {EKG_CHECKLIST.map((cat) => (
            <div key={cat.id} style={{ marginBottom: 20 }}>
              <div
                onClick={() => toggleCat(cat.id)}
                style={{
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                  padding: '12px 16px', borderRadius: 'var(--radius-sm)',
                  background: 'var(--bg-input)', cursor: 'pointer', marginBottom: 8
                }}
              >
                <h3 style={{ fontSize: '0.95rem', fontWeight: 600 }}>{cat.category}</h3>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                    {cat.items.filter(i => checkedItems.includes(i.id)).length}/{cat.items.length}
                  </span>
                  {expandedCat.includes(cat.id) ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                </div>
              </div>
              <AnimatePresence>
                {expandedCat.includes(cat.id) && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.25 }}
                    style={{ display: 'flex', flexDirection: 'column', gap: 6, paddingLeft: 8, overflow: 'hidden' }}
                  >
                    {cat.items.map(item => (
                      <div
                        key={item.id}
                        onClick={() => toggleItem(item.id)}
                        style={{
                          display: 'flex', alignItems: 'flex-start', gap: 12,
                          padding: '10px 14px', borderRadius: 'var(--radius-sm)',
                          border: `1px solid ${checkedItems.includes(item.id) ? 'var(--accent-emerald)' : 'var(--border-subtle)'}`,
                          background: checkedItems.includes(item.id) ? 'var(--accent-emerald-light)' : 'white',
                          cursor: 'pointer', transition: 'all 150ms ease'
                        }}
                      >
                        {checkedItems.includes(item.id)
                          ? <CheckCircle size={18} style={{ color: 'var(--accent-emerald)', flexShrink: 0, marginTop: 1 }} />
                          : <Circle size={18} style={{ color: 'var(--text-muted)', flexShrink: 0, marginTop: 1 }} />
                        }
                        <div style={{ flex: 1 }}>
                          <span style={{ fontSize: '0.875rem', color: 'var(--text-primary)' }}>{item.text}</span>
                          <div style={{ display: 'flex', gap: 6, marginTop: 4 }}>
                            {[...Array(item.weight)].map((_, i) => (
                              <div key={i} style={{
                                width: 6, height: 6, borderRadius: '50%',
                                background: item.weight === 3 ? '#ef4444' : item.weight === 2 ? '#f59e0b' : '#94a3b8'
                              }} />
                            ))}
                            <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)', marginLeft: 4 }}>
                              {item.weight === 3 ? 'Critical' : item.weight === 2 ? 'Important' : 'Nice-to-have'}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}

          <button className="btn btn-primary" onClick={handleEvaluate} style={{ marginTop: 16 }}>
            <TrendingUp size={18} /> Evaluate EKG Health
          </button>
        </div>

        {/* Results */}
        <AnimatePresence>
          {results && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.35 }}
            >
              <div className="stats-bar">
                <div className="stat-card">
                  <ScoreRing score={results.overallScore} size={140} />
                </div>
                {Object.entries(results.categoryScores).map(([cat, score]) => (
                  <div className="stat-card" key={cat} style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                    <div className="stat-value" style={{ color: score >= 70 ? 'var(--accent-emerald)' : score >= 40 ? '#f59e0b' : '#ef4444' }}>
                      {score}%
                    </div>
                    <div className="stat-label">{cat}</div>
                  </div>
                ))}
              </div>

              {/* Radar Chart */}
              {radarData.length >= 3 && (
                <div className="analyzer-form" style={{ marginBottom: 24, padding: '24px 32px' }}>
                  <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: 8, textAlign: 'center' }}>
                    Category Score Distribution
                  </h3>
                  <RadarChart data={radarData} size={320} color="#3b82f6" />
                </div>
              )}

              {results.findings.length > 0 && (
                <div style={{ marginTop: 24 }}>
                  <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: 16 }}>
                    <AlertTriangle size={18} style={{ color: '#f59e0b', marginRight: 8, verticalAlign: 'text-bottom' }} />
                    Findings ({results.findings.length})
                  </h3>
                  <div className="results-section">
                    {results.findings.map((f, i) => (
                      <div key={i} className="result-card" style={{ padding: '16px 20px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                          <span className={`result-severity severity-${f.severity}`}>{f.severity}</span>
                          <div>
                            <p style={{ fontSize: '0.875rem', fontWeight: 500, color: 'var(--text-primary)' }}>{f.issue}</p>
                            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{f.category}</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Export Button */}
              <button
                className="btn btn-secondary"
                onClick={handleExport}
                style={{ marginTop: 24 }}
              >
                <Download size={16} /> Export Report
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
